_episodes/05-remotes.md
https://github.com/coderefinery/git-intro/issues/10
The Remotes and GitHub section focuses more on Bare repositories on a local collaboration. I do not think we use these in real life anymore.
I would like to use a gitbub based example I have, where I add the participants as collaborators (not the fork/pull cycle). User can use a username/password login (ssh key setup not a must). I believe this will be more realistic
=> Moving Github to top of bare repo

_episodes/04-staging-area.md
adding the categories of modified and unmodified files to the checkpointing using the staging area
The differences between git reset and git checkout require these specifications.
At the same time I removed
git reset --soft (which does not lead to any change in the given picture since modifications are neither deleted, nor files are moved from the staging area)
git checkout on unmodified repository (this only replicates the current status)
=> add unmodified/modified to checkpointing

_episodes/12-interrupted.md
Updates to interrupted work.  Most parts minor, some examples and rephrasing.
Would `git merge --abort` be better instead of `git reset --hard`.  Did we use `merge --abort` elsewhere in the talk?
=> interrupted work: Expand stashing and add some proto-exercises

_episodes/11-remotes.md
- Changed to recommend https.  Should change several more places once
I look up right syntax
Also I separate out general discussion of remotes from GitHub.  The general remote stuff could be made much shorter and we give the philosophical discussion later - though this is a good place also, since there are probably some times this is taught but not git-collaborative.
I want to change several more things to https, instead of ssh, if you agree.  I think we shouldn't use ssh unless we teach setting up the keys... which might make sense in git-collaborative.
=> Sharing: update beginning, change ssh to https

guide.md
This works in my personal bash and the Aalto default bash.  The previous problem was caused by having a colorized prompt that puts unprintable characters after the `$`.
There is also now an alias for a prompt starting wiht `$ ` on its own line, but it needs testing.
=> guide: Update the history view commands to work in more cases

guide.md
This info used to be here but it was always relevant to all sections,
now it's moved to manuals repository.
=> guide.md: Move history log instructions to a the manuals repo

_config.yml, reference.md
As discussed in https://github.com/coderefinery/jekyll-common/issues/4
=> display link to reference.md

_episodes/06-branches.md
- Closes: #156
- This is also needed because just `git merge experiment` doesn't work.
=> recipe-branching backup repo: checkout the remote branches to make them local.

_episodes/08-conflicts.md
- Existing manual resolution section could have the actual recipe of
what to do split out.  I also added extra steps of `git status` and
`git diff` in there often, just to clarify.
=> Clarify conflict resolution steps

_config.yml, reference.md
This is currently causing builds to fail, so reverting until it can be
fixed.
This reverts commit 06b11d956d6f0051cae0537b0715c8e68364932c, reversing
changes made to b19aaff4421618231690fdfd04ba494775adc5bb.
=> Revert addition of quick reference

_episodes/14-level.md
- The section was called "Start simple, later increase the level of
complexity" but the name could be a bit better.
- This is not exactly #76 (add a practical tips section) but related.
- I propose that this section be used for practical tips in the future
=> Rename section on complexity and practical tips

_episodes/14-level.md
The section was missing from the table of contents.  Does anyone know
why?  Can anyone make a proper fix really quickly?
This reverts commit fd67e05c2e878c63a8ffb6fe57ba4e110ff2df6b.
=> Missing section because of #164, does anyone know why?

_episodes/14-level.md
issue #76 is about splitting out practical tips. We now have an episode on practical tips, and i think with this commit we take care of the last comments from #76
=> add practical tips 

_episodes/10-archeology.md
background found in #181
this uses a much simpler version of the word-count repo, and hopefully fits better into this context at the same time as it gently introduces the word-count toy project.
=> replace example repo for git archeology and introduce exercise

reference.md
- Normal text combines `--` into a em-dash (–), which can't be copied
and pasted.  Rather than prevent that, I switched to all monospace:
following convention that monospace is something that you type into
the terminal (or the terminal shows you).
=> reference: replace bold commands with monospace

reference.md
* We should emphasize the commands which are always safe to use, and
can be used to figure out what's going on.
* `git graph` is a useful command which is easy to miss, if you don't
see the one place we define it.  Make it and the definition easy to
find.
* This PR depends on and includes my PR of reformatting the bold to
monospace.
=> reference: divide status-checking from other commands, add git graph

_episodes/06-branches.md, guide.md
- State date and version
- Note in instructor's guide that someday, old alternatives can be
de-emphasized
- Closes: #203
=> Improve notes that git-switch and git-restore are new commands

_episodes/04-staging-area.md
- Continue improving my previous refactor, slowly
Two notable commits to check:
staging: under recommendations, include two major strategies
- I always use staging to split out multiple changes that I do at
once (and rarely to incrementally stage things).
- I included one example of both of these major strategies - but is
this too much?  It takes time.  Which do we want to emphasize?.
- I realized that this may be the reason I have a different prototype
example than others: shopping makes more sense for splitting
changes, while boxes makes more sense for incrementally saving!
staging: Initial example: add a daily commit example
- I think it's worth using this opportunity to discuss the major
strategies of committing - I hope it doesn't make it too long.
=> staging: incremental improvements on previous refactor

_episodes/05-undoing.md
[ I'm not sure if this is a worthwhile change yet.  It doesn't
simplify much, but does break it up so that the instructor can more
easily choose which topics to cover, and introduces the idea of
"return to clean repo" as a first step. ]
- Discussion: #232
- Divide episode into four sections:
- checkout -f to get back to clean state
- revert
- commit --amend
- reset --hard $commit_hash
- It's expected that only two would be done in any particular workshop.
- Most of the raw material is the same, just slightly reordered.  I"m
not suer yet if this iis a good idea, but time will tell.
- Closes: #232
=> undoing episode: refactor

_episodes/08-conflicts.md
- "everything" could have meant "one branch for each thing separately".
- Clarify to mean few branches that contain many unrelated changes
=> conflicts: phrasing of "everything"

index.md
- we never have time to go through it before we start
- we have the overview below and a wall of text moves it away from
screen
- time estimates are outdated anyway
- the instructor should be able to introduce the schedule in words
without this text based on the schedule and instructor guide
=> removing text which I think is redundant

_episodes/06-branches.md
Link points to a page that does not exist. The change in this commit fixes the issue.
=> Fix broken link to aliases section

_episodes/06-branches.md
In this sentence, the users who read too fast might think that `git reset --hard` will solve the problem. They will try it, lose everything and re-read the text to finally understand that they got it wrong.
=> Danger in exercise

_episodes/06-branches.md, img/gitink/git-branch-2.svg, img/gitink/git-branch-2.txt
Enhancement to the [create and commit branches exercise](https://coderefinery.github.io/git-intro/06-branches/#exercise-create-and-commit-to-branches)
The work is carried out in the `less-salt` branch.
Then, the text and the output of the `git branch` indicate that the pointer is to the `experiment` branch.
Thus, an instruction to switch branches is needed. 
`git checkout experiment`
Only after this step `git branch` returns
```shell
* experiment
less-salt
master
```
=> add missing instruction to switch branches

_episodes/10-archaeology.md
adapting the example for that to hopefully avoid
this problem
=> it seems git grep on windows needs double quotes; closes #275

_episodes/01-motivation.md
The eht-im repository has switched their naming from `master` to `main`
branch, so the old links didn't work anymore. They should work now.
=> Fix broken eht-imaging links

content/basics.md, content/index.rst
notable changes:
- removed repetitive reference to where the guacamole recipe came from
to have a bit less text
- moved "git log" after the first exercise to have more commits to look
at: earlier we introduced "git log" and only had one commit
=> iteration on "basics" episode

content/archaeology.md
notable change is the history exercise:
- we are looking for a text which is less confusing with an error
message we might get from git
- since we create a branch from a tag, there is no risk that the line
has disappeared so the exercise has now simpler text
- we stay in the networkx example to not switch context too often
=> Update the "history inspection" episode

content/branches.md
notable changes:
- better hints for instructor
- fast-forward merge becomes optional exercise: otherwise risk
is high that instructor goes into a rabbit-hole
- tags move before summary: otherwise we always forget to talk about
tags
- test your understanding: removed question about detached HEAD and
orphaned commits - too early, too much confusion risk
- removed exercises about moving commits to another branch and
squashing: this will be part of "recovering from typical mistakes"
- all in all: just less stuff but hopefully also less distraction
=> work on the "branches" episode

content/basics.md
this is hopefully more robust since then there is less risk of diffing
something that is staged and seeing zero difference
=> example using difftool: make reference to hash; closes #329

content/archaeology.md, content/branches.md, content/conflicts.md, content/interrupted.md
- The `console` parser treats the `$` as special, which makes it not
be selectable when selecting the text for copying and pasting.
`shell` is bash script, which by definition does not have `$` in the
input/outputs.
- I have looked through all episodes and made modifications where needed.
- The only possible downside is this kind of construct:
```
$ git branch experiment master   # create branch called "experiment" from master
$ git checkout experiment        # switch to branch "experiment"
$ git branch                     # list all local branches and show on which branch we are
```
The second line has `#` which gets parsed as a root prompt, not a
comment.  Most of the blocks that aren't marked as console already
had these kind of comments, so maybe it is intentional that they are
not …
=> Change highlighting from `shell` to `console`

requirements.txt
- Makes the copy button exclude `$` prompts.
- Review: check the build, don't merge yet.  Depending on outcome,
this could go straight to sphinx-lesson instead.
=> requirements: Add draft version of sphinx-copybutton which excludes prompts

content/archaeology.md
- do not show `git log -S` in detail, it becomes a side-note (it does not flow well and we don't reuse this)
- avoid empty "$" lines since I find them "ugly"
=> Work on the "archaeology" episode

content/aliases.md
- Only instance of `--cached` which we otherwise don't use.
- `--staged` has been supported since 1.6.1 which is probably safe to
assume people have by now.
- Review: consider if 1.6.1 is old enough
=> content/aliases: for diff, use --staged instead of --cached

content/branches.md
- As #382 said, the `git graph` alias is not empahsized near as much
as it should be!  This is extremely important and all students must
do it or be left behind.
- Update the wording and styling of both the alias definition and the
instructor note.
- Closes: #382
=> content/branches: Make the `git graph` alias important

content/archaeology.md
- Prevents from forming an em-dash instead of two double
- for consistency do the same on other titles on the page
=> content/archaeology: quote `--` in option

content/archaeology.md
- The "never git" message now becomes an "older git" note.
=> content/archaeology: change `switch` on newer git to `checkout` on newer git

content/archaeology.md, content/basics.md, content/branches.md, content/interrupted.md, content/recovering.md, content/reference.md, content/remotes.md, content/staging-area.md
- As discussed in chat (but not yet agreed)
- Ran the command `sed -i -E 's/<([0-9a-zA-Z_-]+)>/\U\1/g'
content/*.md` but also checked each with "meld" and removed cases
that shouldn't be changed (like git command outputs)
- If git command hints use `<var>` maybe that's a reason to not
change?
- Also changed some cases which weren't in angle brackets yet.
- Time taken: about 5 minutes.
- Review
- There's a real chocie here: is this a good idea or not?  I'm not
sure, I've done this to see how hard it would be, not because it
should be done.
- Advantages: perhaps more clear what should be replaced and that
`<>` are not part of the syntax?  Upper case easier to scan and
see?
- Disadvanages: unclear what is a replacement and what is not?  (I
didn't see any places that wolud be the case.) …
=> Change `<var>` to `VAR` throughout

content/remotes.md
- As discussed in an idea
- Installation instructions would still need to be updated
- Review: is correct?  Is simpler?  Is useful?
=> content/remotes: Example of what a SSH or HTTPS selector could look like.

content/configuration.md
- Add `-show-origin` so that people can see where things are defined
(makes it clear where one can change it and this isn't magic)
=> content/configuration: --show-origin for config --list to show insides

content/under-the-hood.md
According to, e.g., [https://git-scm.com/book/en/v2/Git-Internals-Git-Objects](https://git-scm.com/book/en/v2/Git-Internals-Git-Objects), "blobs" are one type of git object, alongside with 'tree objects' and 'commit objects' (and 'tag objects').
I think that calling a commit a 'blob' is a misuse of the term 'blob'. In the git man pages these terms are used with a specific meaning, misnaming things could lead to misunderstanding.
(Awesome material though, I will use it)
=> under-the-hood.md: correction about commit objects

content/under-the-hood.md
I think this is an interesting/useful thing about "git under the hood", since it seems that it can help with avoiding data loss. 
On the other hand, it is just one of many other things that one might find useful.
=> under-the-hood: demo that added file are never lost

CITATION.cff, content/conf.py
=> Add CITATION.cff
