coderefinery/git-intro

_episodes/05-remotes.md
A repetition(as already discussed during branches)  but a good thing to repeat and this time with a remote.
=> Add details on resolving conflicts

_episodes/03-branching.md, _episodes/05-remotes.md
Removed the word "stupid" from text and examples
=> Removed the word "stupid"

_episodes/01-motivation.md
This section is now the starting point into the course and it is very important for me to motivate why we do all this.
=> Rework the motivation part of Git intro

_episodes/01-motivation.md, _episodes/02-basics.md
added an image and tried to make the text somewhat less verbose and more to the point. The goal was to try to establish a mental model of how Git works early in the lesson.
Unfortunately worked on gh-pages originally, so managed to pollute the history a bit...
=> Thor intro edits

_episodes/02-basics.md, _episodes/04-branches.md, _episodes/07-conflicts.md
Make sure that the learners commits are constant with what the text is discussing.
=> Increase consistency between text and exercises 

guide.md, index.md
=> Add instructor guide

_episodes/02-basics.md, _episodes/04-branches.md
This is a good discussion but it fell from the sky in the basics and makes more sense after we have heard about branches.
=> mv discussion of co after branches are introduced; fixes #71

_episodes/09-under-the-hood.md
=> Update under-the-hood episode

_episodes/01-motivation.md
Work in progress. Not to be merged yet but you can have a peek at what I am up to and comment.
=> Updating the motivation part

guide.md
Update the guide based on @bast's initial arrangement and my notes.  Some of the section names and numbers will need updating later.
=> guide.md: Update section description, history log, key points, cheatsheets

_episodes/02-basics.md, _episodes/02-undoing.md
this way it can move to a bit later
=> split "undoing things" to own episode (#72 and #75)

_episodes/08-staging-area.md
- Progress on #81 
I would like to do more revisions on the top portion, around where the two forms of history are shown.  I have a feeling it could be either shortened or made more general (different types of common problems as shown in the issue).  
I think this solves everything from #81 which is needed.
=> Staging area: expand, more analogies and examples

index.md
First attempt at updating the front-page info.  Could use some sanity-checking.
=> Update lesson index with the teaching and course philosophy

_episodes/07-aliases.md
Also makes sure we all add `git graph`.
=> Updates the aliases episode

_episodes/07-aliases.md
- Create the "important" aliases at the beginning
- Add explinations for basic aliases
- Split into basic and advanced, let people do advanced things on
therir own time.
- Note about git aware bash prompt
=> aliases: Reorganization (basic and advanced) and explinations

_episodes/11-remotes.md
- remote = backup
- we really study these in the collabrative lesson
- closes: #79
=> remotes: several key points to implement final suggestions

_episodes/06-staging-area.md
I think we can call #81 closed, but should move some of the remaining stuff into the "practical tips" issue.
=> staging-area: minor formatting fixes

_episodes/01-motivation.md, _episodes/02-existing-repo.md, _episodes/03-basics.md, _episodes/05-undoing.md, _episodes/07-aliases.md, _episodes/10-conflicts.md, _episodes/12-interrupted.md
Stretched the staging to align with lunch time.
=> adjust timing; closes #102

_episodes/06-staging-area.md, _episodes/09-branches.md, _episodes/11-remotes.md, _episodes/12-interrupted.md
=> thor-reykjavik

guide.md
One suggestions from @dgtim, one improvement from me.
=> Improve the bash prompt tails some

.gitignore, _episodes/04-staging-area.md, _episodes/05-undoing.md, _episodes/11-interrupted.md, _episodes/12-aliases.md, _episodes/13-under-the-hood.md, _episodes/14-level.md, _episodes/15-existing-repo.md, guide.md
very unstructured PR, i know... 
I reintroduced the in-browser session as an optional episode which could fit in other types of workshops. Other changes more minor
=> updates before the gothenburg workshop 

_episodes/02-basics.md, _episodes/05-undoing.md, _episodes/06-branches.md
=> splitting optional exercises into smaller more focused exercises 

_episodes/01-motivation.md
- Idea is "it's better to teach by examples", gives grounding to the
problems right below.
=> 01-motivation: Reorder the example dir listing, put it at top of section

reference.md
- Not complete, just for testing purposes while developing the jekyll-common support
- Feel free to change the filename / move it to where it needs to go
=> Initial draft of quick reference

_episodes/05-undoing.md
=> Clarify that you can revert any commit, not only the latest

_episodes/04-staging-area.md
- It needs at least 7 blank lines for it to be split by default
- At least one blank line is enough to use the "s" to split it.
- Closes: #154
=> 04-staging: In interactive exercise, mention blank lines.

_episodes/02-basics.md
This was asked by more than one participant so I thought of adding it here.
=> I have added "press q to quit" after the git help example.

_episodes/02-basics.md, _episodes/08-conflicts.md, _episodes/09-remotes.md
- Clarify when someone should type along with "Type-along:" in section
titles.
- At the beginning of each type-along, say what we will do.
- Bold important terms when they are first introduced.
=> Clarify type-alongs, type-along intros, term definitions.

_episodes/14-level.md
in order to not confuse yaml parser
=> reapply #164, this time quoted

_episodes/05-undoing.md
=> Add a section at the end to clean the experiments with the repo

index.md
Some formatting, use the word "confusing" instead of bad. Short mentioning of undo
=> Instructor guide

index.md
- Closes: #226 (but #226 has a second message about a different topic,
too).
=> link CR installation instructions instead of git upstream

_episodes/10-archeology.md
- #215 (not sure if closes or not)
=> archaeology: Explain how to search and scroll in less

_episodes/04-staging-area.md, img/staging-basics.svg
- Design process: #231
- I was hoping this could be made 10 minutes, but I think that is not
possible with two exercises, no matter how short they are.  What
should we do about it - is it ok?
=> Refactor staging area episode

_episodes/10-archeology.md
- Hopefully better readability
- Show how to clone the example
- Video: recommend one group member to screen-share
=> Minor adjustments for the history inspection lesson

_episodes/01-motivation.md
Adds link to the quote: "Git is a four-handle, dual boiler espresso machine, not instant coffee." 
Note: The quote is already paraphrased. So maybe no need to put it in double quotation.
=> add citation source.

_episodes/06-branches.md
=> addressing issues 

_episodes/04-staging-area.md, _episodes/06-branches.md, _episodes/08-conflicts.md
- Clarify exercises tasks in the first part of the lesson, so that
learners and helpers will clearly know what the expectations are.
- Review: general sanity check.  Minor fact check.
=> Exercise clarifications

_episodes/10-archaeology.md
- @bast
- Adjust exercise introductions so expectations are clear
- Review: sanity check, fact check
=> _episodes/10-archaeology: Clarify exercises some

_episodes/11-interrupted.md
- As in other PRs, clarify the exercises some
- Review: sanity check, fact check
=> _episodes/11-interrupted: exercise clarifications

_episodes/14-level.md
- Add a word to clarify, see diff
- Review: does this even deserve a pull request?
=> _episodes/14-level: Minor edit

_episodes/05-undoing.md
=> _episodes/05-undoing: Make link a markdown link

_episodes/06-branches.md
I am not sure what this refers to so let's better get rid of this.
=> rm half-sentence which seems to be a leftover; closes #265

_episodes/10-archaeology.md
this is to decouple this from forking concept
which may or may not have been introduced at this point
=> we don't need to fork the archaeology exercise

_episodes/06-branches.md
Changes indent level to properly render as a nested enumerated list of code blocks
=> Fix enumerated options in "Test Your Understanding"

content/index.rst
- these are more advanced concepts than branching and merging:
everybody needs to branch and merge but not everybody needs to use the
staging area
- we should spend a bit more time "doing" before we spend 30-45 minutes
undoing
- this introduces "git alias" before we use it
=> move "staging area" and "undoing" to later; closes #248, closes #264

content/index.rst
motivation:
- scroll less
- spend less time on diverging into why github
=> reorder index to move episode list above "why github?"

content/under-the-hood.md
this is never taught but still could be useful in self-study
review: minimal, OK to just merge
=> update the "under the hood" episode

content/reference.md
- This is a more permanent location.
- Review: automerge
=> content/reference: Update cheatsheet link

content/index.rst, content/staging-area.md
What I am confident about:
- episode becomes optional since almost all other episodes are more important to hear or read to get started with Git
What I am unsure about:
- whether the new presentation is helpful or not
- I thought a lot about it but it is not easy to present in one picture even with 3 or 4 levels since the operations change the picture
Even after Git introduced `git restore`, the CLI is still inconsistent, surprising, and confusing. This is not easy to explain.
=> Work on the staging area

content/exercises.md
- sphinx-lesson with the feature is now released
- note: virtualenvs will need to be rebuilt.
- Review:
- Check the preview and make sure it looks good
- CI check
=> content/exercises: Add exercies list directive

content/archaeology.md, content/basics.md, content/branches.md, content/conflicts.md, content/interrupted.md, content/recovering.md, content/staging-area.md
- As the commit title says
- Also make solutions direct descendants of the exercises, where not.
- Review: general check, do all titles seem correct?  Safe to merge
=> Give all exercises names and numbers

content/archaeology.md
=> add hint to get line number; closes #337

content/recovering.md
Solves an ambiguity with respect to referenced commits. Closes #338
=> Clearer references to reverted commit.

content/basics.md, content/conflicts.md
- I had missed these before
- Other conversions I did before seem to work
- Review: automerge
=> Convert several more code blocks to language `console`

content/archaeology.md, content/basics.md, content/branches.md, content/recovering.md, content/remotes.md
- This makes it look a bit nicer and make it clear when code blocks
are part of bullet points.
- Review: automerge
=> Indent code blocks that are part of bulleted lists

content/basics.md, content/index.rst, content/what-to-avoid.md
There are always more things one can avoid but I hope others can add some later.
=> list few gotchas to avoid; closes #298

content/what-to-avoid.md
=> content/what-to-avoid: don't forget to pull before doing new work

content/branches.md
Hopefully all changes improve things. No structural changes. @dhanyapushpadas for info
=> Work on the "branches" episode

content/conflicts.md
review: can be merged after minimal review
=> more emphasis and minor improvements in "conflicts" episode

content/remotes.md
review: can be merged after minimal review
=> minor improvements in "remotes" episode

content/index.rst
- proposal: learner-focused references first - starting with the quick
reference.
- review: automerge
=> content/index: reorder to put 'reference' first in reference section

content/archaeology.md
=> content/archaeology: wording clarification from comment

.gitignore, content/guide.md
=> Add schedule for day one and two to the instructor guide

content/index.rst
- we recommend nano or vs code as editor to start
- avoid repetition in sentences
=> update and shorten the index page

.github/workflows/sphinx.yml
- There should be no changes, but this is more modern and is probably
more secure.
=> .github/workflows/sphinx: Copy newer gh-action from sphinx-lesson-template

content/commits.md
- For a new person, "recording changing" uses less jargon
- This only changes the title of the page, nothing else.  But we
should probabyl use this term when teaching, too.
=> content/commits: Rename title "Commiting changes" -> "Recording changes"
